CREATE TABLE COLA_SFA_Orders(ORDERID varchar(30) primary Key Not Null,
							 ORDER_DATE varchar(20) Null,
							 DELIVERY_DATE varchar(20) Null,
							 SALES_REPID varchar(150) Null,
							 CLIENTID varchar(50) Not Null,
							 CLIENT_NAME varchar(200) Null,
							 CLIENT_ADDRESS varchar(250) Null,							 
							 DTC varchar(20) Null,
							 CLIENTID_DISTRIB varchar(12) Null,
							 FISCAL_NUMBER varchar(20) Null,
							 ACTGRINUM varchar(30) default '1',
							 CITY varchar(150) Null,
							 INPUT_CHANNEL varchar(50) Null
							 )
							 
CREATE TABLE COLA_SFA_Order_Details(ORDERID varchar(30) Not Null,
								    ORDER_DATE varchar(20) Null,
									CLIENTID varchar(50) Not Null,	
									CLIENTID_DISTRIB varchar(12) Null,	 					 							 							 							 
									PRODUCT_CODE varchar(20) Not Null,
									PRODUCT_NAME varchar(250) Not Null,
									QTY_CASES float default 0,							 
									QTY_BOTTLES Float default 0,
									FREE_CASE float default 0,
									DISCOUNT float default 0,
									PRICE_CASE float default 0,
									PRICE_EA float default 0,
									ACTGRINUM varchar(30) default '1',									
									CASES_DISCOUNTED float default 0, 
									DISCOUNT_PROMO_ID varchar(150) null,
									FREE_CASE_PROMO_ID varchar(150) null,
									GROSS_VALUE float default 0,
									INPUT_CHANNEL varchar(50) Null)